[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock

[program:crawler_autothrottle_low]
directory=/app/containers/crawler
process_name=crawler_%(process_num)02d
command=scrapy crawl html_spider -a crawler_id=%(process_num)d --loglevel WARNING
numprocs=7
numprocs_start=0
environment=PYTHONPATH="/app",CRAWLER_USE_AUTOTHROTTLE="true",CRAWLER_CONCURRENT_REQUESTS="256",CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="8",CRAWLER_DOWNLOAD_DELAY="0.25",CRAWLER_AUTOTHROTTLE_START_DELAY="0.5",CRAWLER_AUTOTHROTTLE_MAX_DELAY="10.0",CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="2.0",CRAWLER_AUTOTHROTTLE_DEBUG="false"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=30
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:crawler_canary_07]
directory=/app/containers/crawler
process_name=crawler_07
command=scrapy crawl html_spider -a crawler_id=7 --loglevel WARNING
numprocs=1
environment=PYTHONPATH="/app",CRAWLER_USE_AUTOTHROTTLE="true",CRAWLER_CONCURRENT_REQUESTS="256",CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="8",CRAWLER_DOWNLOAD_DELAY="0.25",CRAWLER_AUTOTHROTTLE_START_DELAY="0.5",CRAWLER_AUTOTHROTTLE_MAX_DELAY="10.0",CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="2.0",CRAWLER_AUTOTHROTTLE_DEBUG="false"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=30
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:crawler_autothrottle_high]
directory=/app/containers/crawler
process_name=crawler_%(process_num)02d
command=scrapy crawl html_spider -a crawler_id=%(process_num)d --loglevel WARNING
numprocs=8
numprocs_start=8
environment=PYTHONPATH="/app",CRAWLER_USE_AUTOTHROTTLE="true",CRAWLER_CONCURRENT_REQUESTS="256",CRAWLER_CONCURRENT_REQUESTS_PER_DOMAIN="8",CRAWLER_DOWNLOAD_DELAY="0.25",CRAWLER_AUTOTHROTTLE_START_DELAY="0.5",CRAWLER_AUTOTHROTTLE_MAX_DELAY="10.0",CRAWLER_AUTOTHROTTLE_TARGET_CONCURRENCY="2.0",CRAWLER_AUTOTHROTTLE_DEBUG="false"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=30
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[group:crawler]
programs=crawler_autothrottle_low,crawler_canary_07,crawler_autothrottle_high
