[supervisord]
nodaemon=true
logfile=/dev/null
pidfile=/tmp/supervisord.pid

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock

[unix_http_server]
file=/tmp/supervisor.sock

[program:router]
directory=/app
process_name=%(program_name)s_%(process_num)02d
command=python -m containers.scheduler_ingest.router.main --config /app/containers/scheduler_ingest/config/ingest.yaml --router-id %(process_num)d
numprocs=%(ENV_NUM_WORKERS)s
numprocs_start=0
environment=PYTHONPATH="/app"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=5
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:ingestor]
directory=/app
process_name=%(program_name)s_%(process_num)02d
command=python -m containers.scheduler_ingest.ingestor.main --config /app/containers/scheduler_ingest/config/ingest.yaml --ingestor-id %(process_num)d
numprocs=%(ENV_NUM_WORKERS)s
numprocs_start=0
environment=PYTHONPATH="/app"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=5
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:feature_extractor]
directory=/app
process_name=%(program_name)s_%(process_num)02d
command=python -m containers.scheduler_ingest.feature_extractor.main --config /app/containers/scheduler_ingest/config/ingest.yaml --extractor-id %(process_num)d
numprocs=%(ENV_NUM_WORKERS)s
numprocs_start=0
environment=PYTHONPATH="/app"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=5
killasgroup=true
stopasgroup=true
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0

[program:stats_aggregator]
directory=/app
command=python -m containers.scheduler_ingest.stats.main --config /app/containers/scheduler_ingest/config/ingest.yaml
environment=PYTHONPATH="/app"
autostart=true
autorestart=true
startretries=20
stopsignal=TERM
stopwaitsecs=5
stdout_logfile=/dev/stdout
stderr_logfile=/dev/stderr
stdout_logfile_maxbytes=0
stderr_logfile_maxbytes=0
